INSERT INTO USERS (USERNAME, EMAIL, NAME, SURNAME, PASSWORD, ROLE,
                   CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
VALUES ('system.admin', 'system.admin@gmail.com', 'System', 'Admin',
        '$2a$10$T398v1AslBL/xMR0ODPxiOcOpX.seTaiE17BCfvnCPV0fd3Tvzr8i', 'ADMIN',
        'SYSTEM', CURRENT_DATE, 'SYSTEM', CURRENT_DATE);


INSERT INTO USERS (USERNAME, EMAIL, NAME, SURNAME, PASSWORD, ROLE,
                   CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
VALUES ('numan.kafadar', 'numankafadar97@gmail.com', 'Numan', 'Kafadar',
        '$2a$10$T398v1AslBL/xMR0ODPxiOcOpX.seTaiE17BCfvnCPV0fd3Tvzr8i', 'STANDART_USER',
        'SYSTEM', CURRENT_DATE, 'SYSTEM', CURRENT_DATE);

INSERT INTO AIRPORT (CITY,CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
VALUES ('Madrid','SYSTEM', CURRENT_DATE, 'SYSTEM', CURRENT_DATE);

INSERT INTO AIRPORT (CITY,CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
VALUES ('İstanbul','SYSTEM', CURRENT_DATE, 'SYSTEM', CURRENT_DATE);

INSERT INTO AIRPORT (CITY,CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
VALUES ('Rome','SYSTEM', CURRENT_DATE, 'SYSTEM', CURRENT_DATE);

INSERT INTO AIRPORT (CITY,CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
VALUES ('London','SYSTEM', CURRENT_DATE, 'SYSTEM', CURRENT_DATE);

INSERT INTO AIRPORT (CITY,CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
VALUES ('Berlin','SYSTEM', CURRENT_DATE, 'SYSTEM', CURRENT_DATE);


-- Two way
INSERT INTO FLIGHT (ARRIVAL_AIRPORT_ID, DEPARTURE_AIRPORT_ID, DEPARTURE_DATE, RETURN_DATE, PRICE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
VALUES (1, 2, TO_TIMESTAMP('2023-09-17 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-09-17 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 300, 'SYSTEM', CURRENT_DATE, 'SYSTEM', CURRENT_DATE);

-- One way
INSERT INTO FLIGHT (ARRIVAL_AIRPORT_ID, DEPARTURE_AIRPORT_ID, DEPARTURE_DATE, RETURN_DATE, PRICE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
VALUES (1, 2, TO_TIMESTAMP('2023-09-17 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 300, 'SYSTEM', CURRENT_DATE, 'SYSTEM', CURRENT_DATE);
